# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

# Generated by Django 5.2.14 on 2026-07-31 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
        ("organizations", "0002_invitation_sent_date"),
        ("webhooks", "0007_remove_retired_organization_delete_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="webhook",
            name="webhooks_project_or_organization",
        ),
        migrations.AlterField(
            model_name="webhook",
            name="type",
            field=models.CharField(
                choices=[
                    ("organization", "ORGANIZATION"),
                    ("project", "PROJECT"),
                    ("instance", "INSTANCE"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("project_id__isnull", False),
                        ("type", "project"),
                    ),
                    models.Q(
                        ("organization_id__isnull", False),
                        ("project_id__isnull", True),
                        ("type", "organization"),
                    ),
                    models.Q(
                        ("organization_id__isnull", True),
                        ("project_id__isnull", True),
                        ("type", "instance"),
                    ),
                    _connector="OR",
                ),
                name="webhooks_project_or_organization_or_instance",
            ),
        ),
    ]
